# Generated by Django 5.2.4 on 2025-07-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cue_anexo', models.CharField(max_length=20)),
                ('nivel', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('modalidad', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=255)),
                ('ambito', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
    ]
